version: '3.8'

services:
  whatsapp-decryptor:
    build: .
    container_name: whatsapp-decryptor
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      - ALLOWED_ORIGINS=http://localhost:5678,https://your-n8n-instance.com
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - n8n-network

networks:
  n8n-network:
    external: true
    name: n8n_default
